Repository ucsb-cs156-s25/proj-rec-s25-15, pull requests merged in 2025-05, with the labels that each got.

#41 Added a get all endpoint for admins
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI

#43 Tw requests tab admin
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminRequestsPage.js
  frontend/src/tests/pages/AdminRequestsPage.test.js
Labels: 10, Merge Candidate-CI

#33 bi - Add request type form component with tests
  frontend/src/fixtures/requestTypeFixtures.js
  frontend/src/main/components/RequestType/RequestTypeForm.js
  frontend/src/stories/components/RequestType/RequestTypeForm.stories.js
  frontend/src/tests/components/RequestType/RequestTypeForm.test.js
Labels: 10

#50 bi - Implement Create page for request types
  frontend/src/App.js
  frontend/src/main/components/RequestType/RequestTypeTable.js
  frontend/src/main/pages/RequestTypes/RequestTypesCreatePage.js
  frontend/src/main/pages/SettingsPage.js
  frontend/src/main/utils/RequestTypeUtils.js
  frontend/src/stories/components/RequestType/RequestTypeTable.stories.js
  frontend/src/stories/pages/RequestTypes/RequestTypesCreatePage.stories.js
  frontend/src/stories/pages/SettingsPage.stories.js
  frontend/src/tests/components/RequestType/RequestTypeTable.test.js
  frontend/src/tests/pages/RequestTypes/RequestTypesCreatePage.test.js
  frontend/src/tests/pages/SettingsPage.test.js
  frontend/src/tests/utils/RequestType.test.js
Labels: 10, Merge Candidate-CI

#35 bi - Modify package.json so it ignores build directory
  frontend/package.json
Labels: 5, Merge Candidate-CI

#54 page for pending request for storybook and main web
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/stories/pages/Requests/PendingRequestsPage.stories.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
Labels: 10, Merge Candidate-CI

#55 dd- proj rec defaultstudent
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/resources/db/migration/changes/Users.json
Labels: 5, Merge Candidate-CI

#57 Dd -remove backend student
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
Labels: 10, Merge Candidate-CI

#59 Yc add tooltips
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
  frontend/src/main/pages/StudentProfile/StudentProfileCreatePage.js
  frontend/src/main/pages/StudentProfile/StudentProfileEditPage.js
  frontend/src/main/pages/StudentProfile/StudentProfileIndexPage.js
  frontend/src/stories/pages/StudentProfile/StudentProfileCreatePage.stories.js
  frontend/src/stories/pages/StudentProfile/StudentProfileEditPage.stories.js
  frontend/src/stories/pages/StudentProfile/StudentProfileIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
  frontend/src/tests/pages/StudentProfile/StudentProfileCreatePage.test.js
  frontend/src/tests/pages/StudentProfile/StudentProfileEditPage.test.js
  frontend/src/tests/pages/StudentProfile/StudentProfileIndexPage.test.js
Labels: 10, Merge Candidate-CI
